#!/usr/bin/env bash
DATE=`date "+%Y-%m-%d-%H.%M.%S"`
if [ -f ~/.gitconfig ]; then
    cp ~/.gitconfig ~/.gitconfig.$DATE
    rm -f ~/.gitconfig
fi
if [ -f ~/.vimrc ]; then
    cp ~/.vimrc ~/.vimrc.$DATE
    rm -f ~/.vimrc
fi
ln -s ~/.vim/.gitconfig ~/.gitconfig
ln -s ~/.vim/.vimrc ~/.vimrc
